// ProgettoTecWeb/src/SmmApp/src/components/gadgets/Squeal.vue
<script lang="ts">
import { getSqueal, deleteSqueal } from '@/services/squeal.service';
import { getCommentSection } from '@/services/comment.service';
import { getRelativeTime } from '@/services/time.service';

export default {
    data() {
        return {
            MAX_CONTENT_LENGTH: 200,
            isTooLong: false,
            isCommentOpen: false,
            isDataOpen: false,
            showMore: false,
            squeal: {} as any,
            comment_section: {} as any,
            loadMoreCommentsButton: true,
            getRelativeTime: getRelativeTime
        };
    },
    props: {
        squeal_id: {
            type: String,
            required: true
        }
    },
    methods: {
        async getSqueal() {
            await getSqueal(this.squeal_id).then(async (response) => {
                this.squeal = response[0];
                if (this.squeal.content_type == 'text' && this.squeal.content.length > this.MAX_CONTENT_LENGTH) {
                    this.isTooLong = true;
                }
            }).catch((error) => {
                console.log(error);
                return error;
            });

        },
        async getCommentSection() {
            await getCommentSection(this.squeal.comment_section).then(async (response) => {
                this.comment_section = response;
            }).catch((error) => {
                console.log(error);
                return error;
            });

        },
        openSquealInNewTab() {
            window.open('/../squeal/' + this.squeal._id, '_blank');
        },
        async loadMoreComments() {
            await getCommentSection(this.squeal.comment_section, this.comment_section.comments_array[0]._id).then(async (response) => {
                response.comments_array.reverse().forEach((element: any) => {
                    this.comment_section.comments_array.unshift(element);
                });
                if (response.comments_array.length <= 0) {
                    this.loadMoreCommentsButton = false;
                }
            }).catch((error) => {
                console.log(error);
                return error;
            });
        },
        async deleteSqueal() {
            await deleteSqueal(this.squeal_id).then(async (response) => {
                this.getSqueal();
            }).catch((error) => {
                console.log(error);
                return error;
            });

        },


    },
    mounted() {
        this.getSqueal()
    }
};
</script>

<template>
    <div class="container text-dark py-3">
        <div class="row justify-content-center">
            <div class="col-10 col-md-8">
                <div class="squeal card text-center shadow-0">

                    <div class="card-header">
                        <div class="row">
                            <div class="col">
                            </div>
                            <div class="col clickable" @click="openSquealInNewTab">
                                HEX {{ squeal.hex_id }}
                            </div>
                            <div class="col text-end" @click="deleteSqueal">
                                <i v-if="squeal.content_type != 'deleted'" class="bi bi-trash" type="button"></i>
                            </div>

                        </div>
                    </div>


                    <div class="card-body p-2 unselectable">
                        <h5 class="card-title">@{{ squeal.username }}</h5>
                        <div v-if="squeal.content_type == 'text'" class="card-text">
                            <p @click="showMore && isTooLong ? showMore = false : null"
                                :class="{ 'clickable': showMore && isTooLong }">
                                {{
                                    isTooLong && !showMore
                                    ? (squeal.content.substring(0, MAX_CONTENT_LENGTH) + "...")
                                    : squeal.content
                                }}
                            </p>
                            <a v-if="isTooLong" class="link clickable" @click="showMore = !showMore">{{
                                showMore ? "...less" : "more..." }}</a>
                        </div>
                        <p v-if="squeal.content_type == 'position' || squeal.content_type == 'deleted'" class="card-text">
                            [{{ squeal.content_type }}]
                        </p>
                        <div class="card-img-top" v-if="squeal.content_type == 'image' || squeal.content_type == 'video'">
                            <img v-if="squeal.content_type == 'image'" :src="'/../media/image/' + squeal.content"
                                class="img-fluid" alt="..." onerror="this.src='/../media/image/not-found.png'">
                            <video v-if="squeal.content_type == 'video'" class="ratio ratio-16x9" controls>
                                <source :src="'/../media/video/' + squeal.content">
                            </video>
                        </div>
                        <!--position-->
                        <div class="w-100">

                        </div>
                        <!--end position-->
                        <div class="card-icons container">
                            <div class="row flex-nowrap justify-content-between d-flex align-items-center my-2">

                                <div class="col-5 px-1">
                                    <button id="comment_button" type="button" class="btn btn-secondary btn-rounded px-2"
                                        v-bind:class="{ 'clicked': isCommentOpen }"
                                        @click="getCommentSection(); isCommentOpen = !isCommentOpen">
                                        <i class="bi bi-chat-dots-fill text-white"></i>
                                        <p class="badge bg-primary ms-2 my-auto">
                                            {{ squeal.comments_count }} </p>
                                    </button>
                                </div>


                                <div class="col-2 p-0 d-flex justify-content-center">
                                </div>

                                <div class="col-5 px-1">
                                    <button type="button" class="btn btn-secondary btn-rounded px-2 py-2"
                                        v-bind:class="{ 'clicked': isDataOpen }" @click="isDataOpen = !isDataOpen">
                                        <i class="bi bi-eye text-white"></i>
                                        <p class="badge bg-primary ms-2 my-auto">
                                            {{ squeal.impressions }} </p>
                                    </button>
                                </div>

                            </div>

                            <div class="flex-nowrap justify-content-center d-flex align-items-center py-2">
                            </div>

                        </div>

                        <div @click="openSquealInNewTab" class="card-footer clickable"><i class="bi bi-calendar4-week"></i>
                            {{ getRelativeTime(squeal.created_at) }}
                        </div>
                        <div class="mt-3" v-if="isDataOpen">
                            <div class="row">
                                <div class="col-3"></div>
                                <div class="col-6">
                                    <div class="row">
                                        <p class="col h5"><b class="h4">👍</b>{{ squeal.reactions?.like || 0 }}</p>
                                        <p class="col h5"><b class="h4">😂</b>{{ squeal.reactions?.laugh || 0 }}</p>
                                        <p class="col h5"><b class="h4">😍</b>{{ squeal.reactions?.love || 0 }}</p>
                                    </div>
                                    <div class="row">
                                        <p class="col h5"><b class="h4">🤮</b>{{ squeal.reactions?.disgust || 0 }}</p>
                                        <p class="col h5"><b class="h4">👎</b>{{ squeal.reactions?.dislike || 0 }}</p>
                                        <p class="col h5"><b class="h4">🙅</b>{{ squeal.reactions?.disagree || 0 }}</p>
                                    </div>
                                </div>
                                <div class="col-3 text-end text-muted ">Total reactions: {{
                                    (squeal.reactions?.positive_reactions +
                                        squeal.reactions?.negative_reactions) || 0 }}</div>
                            </div>
                        </div>
                        <div class="mt-3" v-if="isCommentOpen">
                            <div v-if="loadMoreCommentsButton && squeal.comments_count > 0">
                                <button type="button" @click="loadMoreComments()"
                                    class="btn btn-secondary btn-rounded px-4 py-2">
                                    <i class="bi bi-arrow-down-circle-fill text-white"></i>
                                </button>
                            </div>
                            <div v-if="squeal.comments_count == 0"> No comments yet.</div>
                            <!-- Lista dei commenti -->
                            <ul class="list-unstyled">
                                <li v-for="comment in comment_section.comments_array">
                                    <p class="m-0 mt-2"> <strong> {{ comment.author_username }}: </strong>{{ comment.text }}
                                    </p>
                                    <div>
                                        <small class="text-muted">
                                            {{ comment.timestamp }}
                                        </small>
                                    </div>

                                </li>
                            </ul>

                            <!-- Modulo per aggiungere un nuovo commento -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// ProgettoTecWeb/src/MobileApp/src/app/widgets/squeal/squeal.component.ts
import { Component, Input } from '@angular/core';
import { Squeal } from 'src/app/models/squeal.interface';
import { CommentService } from 'src/app/services/api/comments.service';
import { CommentSection } from 'src/app/models/comment.interface';
import { DarkModeService } from 'src/app/services/dark-mode.service';

@Component({
  selector: 'app-squeal',
  templateUrl: './squeal.component.html',
  styleUrls: ['./squeal.component.css'],
})
export class SquealComponent {
  title = 'Squeal';
  @Input() squeal: Squeal;
  newCommentText: string = '';
  showComments = false;
  loadMore = false;
  comment_section: CommentSection = {};

  constructor(private commentService: CommentService, private darkModeService: DarkModeService) {
    this.squeal = {};
  }

  getThemeClass() {
    return this.darkModeService.getThemeClass();
  }

  showLoadMore() {
    if (this.squeal.comments_count && this.squeal.comment_section) {
      this.loadMore = Number(this.squeal.comments_count) > (this.comment_section.comments_array?.length || 0);
    } else {
      this.loadMore = false;
    }
  }

  toggleComments() {
    this.showLoadMore();
    this.showComments = !this.showComments;
    if (this.showComments) {
      // Ottieni i commenti
      this.commentService.getComments(this.squeal.comment_section || '').subscribe(
        (response: any) => {
          console.log(response);
          this.comment_section = response;
        },
        (error) => {
          console.error(error);
        }
      );
    }
  }

  loadMoreComments() {
    this.showLoadMore();

    console.log('loadMoreComments');
    if (this.comment_section.comments_array && this.comment_section.comments_array.length > 0) {
      this.commentService
        .getComments(this.squeal.comment_section || '', this.comment_section.comments_array[0]._id)
        .subscribe(
          (response: any) => {
            console.log(response);
            this.comment_section.comments_array?.unshift(...response.comments_array);
          },
          (error) => {
            console.error(error);
          }
        );
    }
  }

  addComment() {
    console.log(this.newCommentText);
    this.commentService.addComment(this.squeal.comment_section || '', this.newCommentText).subscribe(
      (response: any) => {
        console.log(response);
        this.comment_section.comments_array?.push(response.comment);
        this.newCommentText = '';
      },
      (error) => {
        console.error(error);
      }
    );
  }
}

<div *ngIf="isSquealPage" class="my-2"><i class="bi bi-arrow-left-circle-fill clickable" (click)="goBack()"></i></div>
<div class="container of-vis mb-2">
  <div class="row justify-content-center of-vis">
    <div class="col-12 col-md-6 of-vis">
      <div class="squeal card text-center shadow-0 of-vis" [class]="getDarkMode()">

        <div class="card-header">
          <div class="row">
            <div class="col">
            </div>
            <div class="col clickable" (click)="squeal.content_type!='deleted' ? goToSqueal() : null">
              <i *ngIf="squeal.is_in_official_channel" class="bi bi-award-fill text-warning"></i> HEX{{squeal.hex_id}}
            </div>
            <div class="col text-end">
              <i *ngIf="mySqueal && squeal.content_type != 'deleted' && isProfile" class="bi bi-trash" type="button"
                data-bs-toggle="modal" data-bs-target="#deleteConfirm" [attr.data-bs-squealId]="squeal._id"></i>
            </div>

          </div>
        </div>


        <div class="card-body p-2 of-vis">
          <h5 class="card-title">@{{squeal.username}}</h5>
          <p *ngIf="squeal.content_type == 'text' || squeal.content_type == 'deleted'" class="card-text mb-1"
            (click)="(squeal.content && squeal.content.length > TRUNCATE_LENGTH && showMore) ? showMore = false : null"
            [class.clickable]="squeal.content && squeal.content.length > TRUNCATE_LENGTH && showMore">
            {{showMore ? squeal.content : (squeal.content?.substring(0, TRUNCATE_LENGTH))}}
            {{squeal.content && squeal.content.length> TRUNCATE_LENGTH && !showMore ? "..." : ""}}
          </p>
          <a *ngIf="squeal.content && squeal.content.length > TRUNCATE_LENGTH" class="clickable link mb-2"
            (click)="showMore = !showMore">{{showMore ?"...less" : "more..."}}</a>

          <div *ngIf="squeal.content_type == 'image'" class="card-img-top ">
            <img [src]="squeal.content?.startsWith('https')?squeal.content:('media/image/'+squeal.content)"
              alt="Uploaded image" class="img-fluid" onerror="this.src='/../media/image/not-found.png'" />
          </div>
          <div *ngIf="squeal.content_type == 'video'">
            <video controls [poster]="'media/thumbnail/'+squeal.content" style="max-width: 100%; height: auto;"
              preload="auto" playsinline>
              <source [src]="'media/video/'+squeal.content" type="video/mp4">
            </video>
          </div>
          <!--position-->
          <div *ngIf="squeal.content_type == 'position'" class="w-100">
            <app-map [squeal_content]="squeal.content || ''" [lng]="getLon(squeal.content)"
              [lat]="getLat(squeal.content)" [squeal_id]="squeal._id || '0'" class="w-100"></app-map>
          </div>
          <!--end position-->
          <div *ngIf="squeal.content_type!='deleted'" class="card-icons container">
            <div class="row flex-nowrap justify-content-between d-flex align-items-center my-2 buttons-container">

              <div class="col-5 px-1">
                <button [id]="'comment_button'+squeal._id" type="button" title="toggle comments section"
                  class="btn btn-secondary comments btn-rounded px-2" (click)="isGuest?null:toggleComments()"
                  data-bs-toggle="button" [disabled]="isGuest">
                  <i class="bi bi-chat-dots-fill"></i>
                  <p class="badge bg-danger ms-2 my-auto">{{squeal.comments_count || 0}}</p>
                </button>
              </div>


              <div class="col-2 p-0 d-flex justify-content-center reaction-container">
                <app-reactions-menu (reaction)="handleReactionAdd($event)" [alreadyReacted]="squeal.reacted || false"
                  [squealId]="squeal._id ?? '0'" [isGuest]="isGuest" class="on-top"></app-reactions-menu>
              </div>

              <div class="col-5 px-1">
                <button title="report a squeal" (click)="reportSqueal()" type="button"
                  class="btn btn-secondary btn-rounded report px-4 py-2" data-bs-toggle="button" [disabled]="isGuest">
                  <i class="bi bi-flag-fill"></i>
                </button>
              </div>

            </div>
            <div *ngIf="isSquealPage" class="row">
              <div class="col-6">
                <div class="row">
                  <h3 class="col-9 text-end m-0 p-0 b-0"> {{squeal.reactions?.dislike?.toLocaleString()}} </h3>
                  <h3 class="col text-start m-0 p-0 b-0"> 👎 </h3>
                </div>
                <div class="row">
                  <h3 class="col-9 text-end m-0 p-0 b-0"> {{squeal.reactions?.disagree?.toLocaleString()}} </h3>
                  <h3 class="col text-start m-0 p-0 b-0"> 🙅 </h3>
                </div>
                <div class="row">
                  <h3 class="col-9 text-end m-0 p-0 b-0"> {{squeal.reactions?.disgust?.toLocaleString()}} </h3>
                  <h3 class="col text-start m-0 p-0 b-0"> 🤮 </h3>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <h3 class="col text-end m-0 p-0 b-0"> 👍 </h3>
                  <h3 class="col-9 text-start m-0 p-0 b-0"> {{squeal.reactions?.like?.toLocaleString()}} </h3>
                </div>
                <div class="row">
                  <h3 class="col text-end m-0 p-0 b-0"> 😂 </h3>
                  <h3 class="col-9 text-start m-0 p-0 b-0"> {{squeal.reactions?.laugh?.toLocaleString()}} </h3>
                </div>
                <div class="row">
                  <h3 class="col text-end m-0 p-0 b-0"> 😍 </h3>
                  <h3 class="col-9 text-start m-0 p-0 b-0"> {{squeal.reactions?.love?.toLocaleString()}} </h3>
                </div>
              </div>
            </div>
            <div *ngIf="isHome" class="flex-nowrap justify-content-center d-flex align-items-center py-2 below">
              <div *ngIf="squeal.selected?.because=='mentioned'">
                <ul class="list-group list-group-horizontal">
                  <li class="list-group-item" [class.bg-secondary]="getDarkMode()=='dark-theme'"
                    [class.text-light]="getDarkMode()=='dark-theme'">You have been mentioned here</li>
                </ul>
              </div>
              <div *ngIf="squeal.selected?.because=='official' || squeal.selected?.because=='subscribed'">
                <ul class="list-group list-group-horizontal">
                  <li (click)="goToChannel(name)" *ngFor="let name of squeal.selected?.ids"
                    class="list-group-item clickable" [class.bg-secondary]="getDarkMode()=='dark-theme'"
                    [class.text-light]="getDarkMode()=='dark-theme'">
                    §{{name}}</li>
                </ul>
              </div>

            </div>

          </div>

          <div *ngIf="squeal.content_type!='deleted'" class="card-footer clickable" (click)="goToSqueal()"><i
              class="bi bi-calendar4-week"></i>
            {{timeService.getRelativeTime(squeal.created_at)}}</div>
          <div *ngIf="squeal.content_type=='deleted'" class="card-footer"><i class="bi bi-trash-fill"></i>
            {{timeService.getRelativeTime(squeal.last_modified)}}</div>
          <div *ngIf="showComments" class="mt-3">
            <h4>Comments</h4>
            <button class="btn btn-secondary pb-2" *ngIf="loadMore" (click)="loadMoreComments()">Load more</button>
            <!-- Comment list -->
            <ul class="list-unstyled pt-2">
              <li *ngFor="let comment of comment_section.comments_array">
                <p class="mb-1"><strong>{{comment.author_username}}</strong>: {{comment.text}}</p>
              </li>
            </ul>

            <!-- Add more comments form -->

            <form class="input-group mb-3">
              <input type="text" [(ngModel)]="newCommentText" class="form-control" name="squeal comment"
                placeholder="Insert your comment..." aria-label="Recipient's username"
                aria-describedby="comment post button">
              <button class="btn btn-outline-secondary" type="submit" (click)="addComment()"
                id="commentPostButton">Post</button>
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<div *ngIf="isSquealPage && showLoginMessage" class="m-2 d-flex justify-content-center">
  <p><a href="/login" class="link">Log-in</a> with your account or as guest if you want to react!</p>
</div>
